将鱼图像数据进行操作，使用numpy知识

# Pandas的数据结构



导入pandas：  
三剑客

In [1]:
import numpy as np


import pandas as pd
from pandas import Series,DataFrame


import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
# pandas 基于numpy

### 1、Series

Series是一种类似与一维数组的对象，由下面两个部分组成：
- values：一组数据（ndarray类型）
- index：相关的数据索引标签

#### 1）Series的创建

两种创建方式：

(1) 由列表或numpy数组创建

    默认索引为0到N-1的整数型索引

In [4]:
nd = np.random.randint(0,150,size = 5)

s = Series(data = nd,index = ['a','b','c','d','e'],name = 'Python')
s

a    111
b    107
c    147
d    114
e     39
Name: Python, dtype: int32

    还可以通过设置index参数指定索引

特别地，由ndarray创建的是引用，而不是副本。对Series元素的改变也会改变原来的ndarray对象中的元素。（列表没有这种情况）

(2) 由字典创建

In [6]:
s2 = Series(data = {'a':100,'b':120,'c':118,'d':69,'e':88},name = 'Java')
s2

a    100
b    120
c    118
d     69
e     88
Name: Java, dtype: int64

In [7]:
display(type(nd),type(s))

numpy.ndarray

pandas.core.series.Series

In [8]:
# 从Series中取出的数据就是ndarray
s.values

array([111, 107, 147, 114,  39])

============================================

练习1：

使用多种方法创建以下Series，命名为s1：  
语文 150   
数学 150   
英语 150   
理综 300   

============================================

#### 2）Series的索引和切片

可以使用中括号取单个索引（此时返回的是元素类型），或者中括号里一个列表取多个索引（此时返回的仍然是一个Series类型）。分为显示索引和隐式索引：

(1) 显式索引：

    - 使用index中的元素作为索引值
    - 使用.loc[]（推荐）

 注意，此时是闭区间

In [13]:
s

a    111
b    107
c    147
d    114
e     39
Name: Python, dtype: int32

In [19]:
# 一个数
s['a']

numpy.int32

In [15]:
# 多个数据，返回的是Series
s[['a','d']]

a    111
d    114
Name: Python, dtype: int32

In [20]:
s[['e']]

e    39
Name: Python, dtype: int32

In [21]:
s.loc['a']

111

In [22]:
s.loc[['a','c']]

a    111
c    147
Name: Python, dtype: int32

(2) 隐式索引：

    - 使用整数作为索引值
    - 使用.iloc[]（推荐）

 注意，此时是半开区间

In [24]:
s[3]

114

In [25]:
s.iloc[2]

147

In [26]:
s['a':'c']

a    111
b    107
c    147
Name: Python, dtype: int32

In [27]:
s.loc['a':'c']

a    111
b    107
c    147
Name: Python, dtype: int32

In [28]:
s

a    111
b    107
c    147
d    114
e     39
Name: Python, dtype: int32

In [29]:
s.iloc[0:2]

a    111
b    107
Name: Python, dtype: int32

In [30]:
s[0:2]

a    111
b    107
Name: Python, dtype: int32

============================================

练习2：

使用多种方法对练习1创建的Series s1进行索引和切片：

索引：
数学 150 

切片：
语文 150 
数学 150 
英语 150 

============================================

#### 3）Series的基本概念

可以把Series看成一个定长的有序字典

可以通过shape，size，index,values等得到series的属性

In [31]:
s.shape

(5,)

In [32]:
s.size

5

In [33]:
s.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [34]:
s.values

array([111, 107, 147, 114,  39])

可以通过head(),tail()快速查看Series对象的样式

In [35]:
s2 = Series(np.random.randint(0,100000,size = 5000))
s2

0       76339
1       78036
2       35470
3        6410
4       21255
5       13792
6       27290
7       52477
8        5437
9       19894
10      47483
11      60743
12      89186
13       8088
14       3101
15      91878
16      76637
17       7484
18      80563
19      36389
20       8720
21      36231
22      17726
23      64560
24      24343
25      96652
26      67862
27      32071
28      30864
29      45034
        ...  
4970    24359
4971    87906
4972    52055
4973    11417
4974     3884
4975    87195
4976    48073
4977    28172
4978    56207
4979     9432
4980    50417
4981    94646
4982      272
4983    95235
4984    74562
4985    69844
4986    23124
4987    63204
4988    23519
4989      209
4990    31049
4991    23027
4992    75968
4993    85494
4994    91293
4995    42508
4996    47852
4997    62956
4998     6881
4999    14800
Length: 5000, dtype: int32

In [38]:
s2.tail(n = 10)

4990    31049
4991    23027
4992    75968
4993    85494
4994    91293
4995    42508
4996    47852
4997    62956
4998     6881
4999    14800
dtype: int32

In [39]:
s2.head()

0    76339
1    78036
2    35470
3     6410
4    21255
dtype: int32

当索引没有对应的值时，可能出现缺失数据显示NaN（not a number）的情况

In [43]:
s = Series(np.random.randint(0,150,size = 6),index=list('abcdef'))
# Python 中数据类型None
s['f'] = None

In [44]:
s

a    23.0
b    54.0
c    67.0
d     5.0
e    11.0
f     NaN
dtype: float64

In [45]:
s['a'] = np.nan
s

a     NaN
b    54.0
c    67.0
d     5.0
e    11.0
f     NaN
dtype: float64

In [47]:
s.values.sum()

nan

In [48]:
# Series中虽然有非数字数据，依然可以进行计算
s.sum()

137.0

可以使用pd.isnull()，pd.notnull()，或自带isnull(),notnull()函数检测缺失数据

In [49]:
# s 数据6个数据，哪些数据是空
# isnull() 哪些是空，是空，True；不是空False
pd.isnull(s)

a     True
b    False
c    False
d    False
e    False
f     True
dtype: bool

In [50]:
# notnull()和isnull()相反
pd.notnull(s)

a    False
b     True
c     True
d     True
e     True
f    False
dtype: bool

In [51]:
s.isnull()

a     True
b    False
c    False
d    False
e    False
f     True
dtype: bool

In [55]:
cond = s.notnull()

# 根据选出来不为空的数据
s[cond].astype(np.int8)

b    54
c    67
d     5
e    11
dtype: int8

In [58]:
s2 = s[cond].astype(np.int8)
s2.isnull().any()

False

In [56]:

# Series中确实存在空数据
s.isnull().any()

True

In [59]:
s.notnull().all()

False

In [62]:
s2.notnull().all()

True

Series对象本身及其实例都有一个name属性

In [64]:
# 取出重复元素
s2.unique()

array([54, 67,  5, 11], dtype=int64)

In [66]:
s3 = Series(np.random.randint(0,10,size = 100))
s3

0     0
1     2
2     1
3     2
4     4
5     7
6     7
7     8
8     4
9     4
10    2
11    4
12    5
13    8
14    1
15    0
16    8
17    9
18    5
19    9
20    9
21    0
22    7
23    1
24    8
25    0
26    8
27    9
28    7
29    7
     ..
70    2
71    0
72    2
73    8
74    4
75    9
76    8
77    3
78    7
79    7
80    0
81    0
82    7
83    8
84    8
85    9
86    7
87    4
88    0
89    8
90    0
91    3
92    2
93    3
94    4
95    4
96    0
97    2
98    5
99    4
Length: 100, dtype: int32

In [67]:
s3.unique()

array([0, 2, 1, 4, 7, 8, 5, 9, 6, 3], dtype=int64)

#### 4）Series的运算

(1) 适用于numpy的数组运算也适用于Series

In [70]:
s2 * 10

b     28
c    -98
d     50
e    110
dtype: int8

(2) Series之间的运算

- 在运算中自动对齐不同索引的数据
- 如果索引不对应，则补NaN

- 注意：要想保留所有的index，则需要使用.add()函数

In [71]:
s1 = Series(np.random.randint(0,10,size = 5),list('abced'))
s2 = Series(np.random.randint(-10,30,size =5),list('abced'))
display(s1,s2)

a    5
b    3
c    1
e    5
d    4
dtype: int32

a    13
b    -1
c    17
e    10
d    21
dtype: int32

In [72]:
s1 + s2

a    18
b     2
c    18
e    15
d    25
dtype: int32

In [73]:
s3 = Series(np.random.randint(-10,50,size= 5),list('bcdef'))
s3

b    34
c    41
d     5
e    -8
f    25
dtype: int32

In [74]:
# Series进行相加时，索引不同，使用Python运算符，会自动，补NaN
s1 + s3

a     NaN
b    37.0
c    42.0
d     9.0
e    -3.0
f     NaN
dtype: float64

In [76]:
10 + np.nan

nan

In [77]:
10 + np.NaN

nan

In [78]:
10 + np.NAN

nan

In [80]:
# fill_value如果没有该索引，填充的值
s1.add(s3,fill_value=0)

a     5.0
b    37.0
c    42.0
d     9.0
e    -3.0
f    25.0
dtype: float64

============================================

练习3：

1. 想一想Series运算和ndarray运算的规则有什么不同？

2. 新建另一个索引包含“文综”的Series s2，并与s2进行多种算术操作。思考如何保存所有数据。

============================================

### 2、DataFrame

DataFrame是一个【表格型】的数据结构，可以看做是【由Series组成的字典】（共用同一个索引）。DataFrame由按一定顺序排列的多列数据组成。设计初衷是将Series的使用场景从一维拓展到多维。DataFrame既有行索引，也有列索引。
- 行索引：index
- 列索引：columns
- 值：values（numpy的二维数组）

#### 1）DataFrame的创建
最常用的方法是传递一个字典来创建。DataFrame以字典的键作为每一【列】的名称，以字典的值（一个数组）作为每一列。

此外，DataFrame会自动加上每一行的索引（和Series一样）。

同Series一样，若传入的列与字典的键不匹配，则相应的值为NaN。


In [ ]:
Series()

In [9]:
df = DataFrame(data = np.random.randint(0,150,size = (5,3)),index=list('abcde'),columns=['Python','数学','Java'])
df

Python   数学  Java
a       6  142    89
b       1  117    90
c      19  106    37
d      42  125    81
e     119   11   101

In [10]:
df2 = DataFrame(data={'Python':np.random.randint(0,150,size = 5),'数学':np.random.randint(0,150,size = 5),'En':np.random.randint(0,150,size = 5)},
               index = list('ABCDE'))
df2

Python   数学   En
A     110  113   57
B      88  107   46
C      20   15  148
D       2  122   92
E      40    1    9

In [11]:
display(s,df)

a    111
b    107
c    147
d    114
e     39
Name: Python, dtype: int32

Python   数学  Java
a       6  142    89
b       1  117    90
c      19  106    37
d      42  125    81
e     119   11   101

In [12]:
# DataFrame是多个Series集合
# Series处理一维数据，DataFrame处理二维的数据
df['数学']

a    142
b    117
c    106
d    125
e     11
Name: 数学, dtype: int32

DataFrame属性：values、columns、index、shape

============================================

练习4：

根据以下考试成绩表，创建一个DataFrame，命名为df：
```
    张三  李四
语文 150  0
数学 150  0
英语 150  0
理综 300  0
```

============================================

#### 2）DataFrame的索引

(1) 对列进行索引

    - 通过类似字典的方式
    - 通过属性的方式

 可以将DataFrame的列获取为一个Series。返回的Series拥有原DataFrame相同的索引，且name属性也已经设置好了，就是相应的列名。

In [ ]:
# DataFrame 像Excel表格
# SAS SPSS 大型数据处理软件，Excel：表格结构

# pandas中DataFrame功能强大的数据处理工具
# DataFrame表格结构样式
# DataFrame行和列的索引方式不同的

# 列 相当于属性
# 行 相当于样本
# 列 更加重要

In [82]:
# 数据类型Series
df['Java']

a     89
b     90
c     37
d     81
e    101
Name: Java, dtype: int32

In [83]:
df[['Java','数学']]

Java   数学
a    89  142
b    90  117
c    37  106
d    81  125
e   101   11

In [84]:
df[['Python']]

Python
a       6
b       1
c      19
d      42
e     119

(2) 对行进行索引

    - 使用.ix[]来进行行索引
    - 使用.loc[]加index来进行行索引
    - 使用.iloc[]加整数来进行行索引
    
 同样返回一个Series，index为原来的columns。

In [86]:
df['a']

KeyError: 'a'

In [87]:
df.ix['a']

C:\Users\softpo.DESKTOP-PN692CT\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


Python      6
数学        142
Java       89
Name: a, dtype: int32

In [89]:
df.loc[['a','e']]

Python   数学  Java
a       6  142    89
e     119   11   101

In [90]:
df.loc[['a']]

Python   数学  Java
a       6  142    89

In [91]:
df.iloc[0]

Python      6
数学        142
Java       89
Name: a, dtype: int32

In [93]:
df.iloc[[0,3]]

Python   数学  Java
a       6  142    89
d      42  125    81

(3) 对元素索引的方法
    - 使用列索引
    - 使用行索引(iloc[3,1]相当于两个参数;iloc[[3,3]] 里面的[3,3]看做一个参数)
    - 使用values属性（二维numpy数组）

In [94]:
df

Python   数学  Java
a       6  142    89
b       1  117    90
c      19  106    37
d      42  125    81
e     119   11   101

In [96]:
df['数学']['b']

117

In [98]:
df.loc['b']['数学']

117

In [99]:
# axis = 0 行
# axis =1 列
# DataFrame中loc获取行，
df.loc['b','数学']

117

In [100]:
# 列索引不支持，二维的查找
df['数学','b']

KeyError: ('数学', 'b')

【注意】
直接用中括号时：
- 索引表示的是列索引
- 切片表示的是行切片

In [102]:
# 切片
df.loc['a':'c']

Python   数学  Java
a       6  142    89
b       1  117    90
c      19  106    37

In [103]:
# 数字，进行切片，此时左闭右开，索引2取不到
df.iloc[0:2]

Python   数学  Java
a       6  142    89
b       1  117    90

In [108]:
# 对列进行切片
df['Python1':'数学2']

Python   数学  Java
a       6  142    89
b       1  117    90
c      19  106    37
d      42  125    81
e     119   11   101

In [119]:
df['Python333':'语文']

Python   数学  Java
a       6  142    89
b       1  117    90
c      19  106    37
d      42  125    81
e     119   11   101

In [120]:
# 直接使用[]进行切片，不能切列，只能切行
df['a':'c']


Python   数学  Java
a       6  142    89
b       1  117    90
c      19  106    37

In [121]:
df['a':'z']

Python   数学  Java
a       6  142    89
b       1  117    90
c      19  106    37
d      42  125    81
e     119   11   101

In [122]:
df['z':]

Empty DataFrame
Columns: [Python, 数学, Java]
Index: []

In [123]:
# 对列进行切片只有一个办法
# iloc[],第一个冒号，代表行都保留；第二个冒号，切割列
df.iloc[:,1:]

数学  Java
a  142    89
b  117    90
c  106    37
d  125    81
e   11   101

In [124]:
df = DataFrame(np.random.randint(0,150,size = (6,6)),index=list('ABCDEF'),columns=['Python','数学','En','Chinese','理综','文综'])
df

Python   数学   En  Chinese   理综   文综
A     102  141   10      103  132  143
B     129  103   59       26   12   58
C     136   56  107      116   46   60
D       6    7   54      132   46   51
E     146   25   36       53  142   88
F      43   48  111      134   15   82

In [126]:
df.iloc[:,2:-1]

En  Chinese   理综
A   10      103  132
B   59       26   12
C  107      116   46
D   54      132   46
E   36       53  142
F  111      134   15

In [127]:
df[['En','Chinese','理综']]

En  Chinese   理综
A   10      103  132
B   59       26   12
C  107      116   46
D   54      132   46
E   36       53  142
F  111      134   15

============================================

练习5：

使用多种方法对ddd进行索引和切片，并比较其中的区别

============================================

#### 3）DataFrame的运算

（1） DataFrame之间的运算

同Series一样：

- 在运算中自动对齐不同索引的数据
- 如果索引不对应，则补NaN

创建DataFrame df1 不同人员的各科目成绩，月考一

In [132]:
df / 10

Python    数学    En  Chinese    理综    文综
A    10.2  14.1   1.0     10.3  13.2  14.3
B    12.9  10.3   5.9      2.6   1.2   5.8
C    13.6   5.6  10.7     11.6   4.6   6.0
D     0.6   0.7   5.4     13.2   4.6   5.1
E    14.6   2.5   3.6      5.3  14.2   8.8
F     4.3   4.8  11.1     13.4   1.5   8.2

In [133]:
df1 = DataFrame(np.random.randint(0,150,size = (6,4)),index=list('ABCDEF'),columns=['Python','数学','En','Chinese'])
df1

Python   数学   En  Chinese
A     106   90   26      140
B     142  125  147       90
C       7   56  138       80
D      97   87   27       59
E     140   83   13       58
F      65   27   42       75

创建DataFrame df2 不同人员的各科目成绩，月考二  
有新学生转入

In [134]:
df2 = DataFrame(np.random.randint(0,150,size = (6,4)),index=list('ABCDEF'),columns=['Python','数学','En','Chinese'])

df2

Python   数学   En  Chinese
A      99   89   74       25
B      15  121   35       39
C      24   33    1       60
D      71  110  108       87
E     145   87   71       17
F     144   83  105       33

In [136]:
# ndarray  astype(np.int)
((df1 + df2)/2).astype(np.int16)

Python   数学  En  Chinese
A     102   89  50       82
B      78  123  91       64
C      15   44  69       70
D      84   98  67       73
E     142   85  42       37
F     104   55  73       54

In [137]:
df3 = DataFrame(np.random.randint(0,150,size = (7,4)),index=list('ABCDEFG'),columns=['Python','数学','En','Chinese'])
df3

Python   数学   En  Chinese
A      95   78   81      142
B      50   68  104       65
C      13   17   49        5
D      87   20   60      117
E     148   32  148       56
F     112   61   98      116
G      38  127   41       65

In [138]:
df1 + df3

Python     数学     En  Chinese
A   201.0  168.0  107.0    282.0
B   192.0  193.0  251.0    155.0
C    20.0   73.0  187.0     85.0
D   184.0  107.0   87.0    176.0
E   288.0  115.0  161.0    114.0
F   177.0   88.0  140.0    191.0
G     NaN    NaN    NaN      NaN

下面是Python 操作符与pandas操作函数的对应表：

| Python Operator | Pandas Method(s)                      |
|-----------------|---------------------------------------|
| ``+``           | ``add()``                             |
| ``-``           | ``sub()``, ``subtract()``             |
| ``*``           | ``mul()``, ``multiply()``             |
| ``/``           | ``truediv()``, ``div()``, ``divide()``|
| ``//``          | ``floordiv()``                        |
| ``%``           | ``mod()``                             |
| ``**``          | ``pow()``                             |


In [144]:
df4 = df1.add(df3,fill_value=0)
df4

Python     数学     En  Chinese
A   201.0  168.0  107.0    282.0
B   192.0  193.0  251.0    155.0
C    20.0   73.0  187.0     85.0
D   184.0  107.0   87.0    176.0
E   288.0  115.0  161.0    114.0
F   177.0   88.0  140.0    191.0
G    38.0  127.0   41.0     65.0

In [153]:
df4.loc['A':'F']/2
df4

Python     数学     En  Chinese
A   201.0  168.0  107.0    282.0
B   192.0  193.0  251.0    155.0
C    20.0   73.0  187.0     85.0
D   184.0  107.0   87.0    176.0
E   288.0  115.0  161.0    114.0
F   177.0   88.0  140.0    191.0
G    38.0  127.0   41.0     65.0

In [148]:
df5 = df4.iloc[0:6]/2
df5

Python    数学     En  Chinese
A   100.5  84.0   53.5    141.0
B    96.0  96.5  125.5     77.5
C    10.0  36.5   93.5     42.5
D    92.0  53.5   43.5     88.0
E   144.0  57.5   80.5     57.0
F    88.5  44.0   70.0     95.5

In [150]:
df6 = df4.loc[['G']]
df6

Python     数学    En  Chinese
G    38.0  127.0  41.0     65.0

In [151]:
# append 列表类似的
df5.append(df6)

Python     数学     En  Chinese
A   100.5   84.0   53.5    141.0
B    96.0   96.5  125.5     77.5
C    10.0   36.5   93.5     42.5
D    92.0   53.5   43.5     88.0
E   144.0   57.5   80.5     57.0
F    88.5   44.0   70.0     95.5
G    38.0  127.0   41.0     65.0

（2） Series与DataFrame之间的运算

【重要】

- 使用Python操作符：以行为单位操作（参数必须是行），对所有行都有效。（类似于numpy中二维数组与一维数组的运算，但可能出现NaN）

- 使用pandas操作函数：

        axis=0：以列为单位操作（参数必须是列），对所有列都有效。
        axis=1：以行为单位操作（参数必须是行），对所有行都有效。

In [154]:
df1

Python   数学   En  Chinese
A     106   90   26      140
B     142  125  147       90
C       7   56  138       80
D      97   87   27       59
E     140   83   13       58
F      65   27   42       75

In [155]:
s = df1['Python']
s

A    106
B    142
C      7
D     97
E    140
F     65
Name: Python, dtype: int32

In [156]:
df1 + s

A   B   C  Chinese   D   E  En   F  Python  数学
A NaN NaN NaN      NaN NaN NaN NaN NaN     NaN NaN
B NaN NaN NaN      NaN NaN NaN NaN NaN     NaN NaN
C NaN NaN NaN      NaN NaN NaN NaN NaN     NaN NaN
D NaN NaN NaN      NaN NaN NaN NaN NaN     NaN NaN
E NaN NaN NaN      NaN NaN NaN NaN NaN     NaN NaN
F NaN NaN NaN      NaN NaN NaN NaN NaN     NaN NaN

In [165]:
display(df1,s)

Python   数学   En  Chinese
A     106   90   26      140
B     142  125  147       90
C       7   56  138       80
D      97   87   27       59
E     140   83   13       58
F      65   27   42       75

A    106
B    142
C      7
D     97
E    140
F     65
Name: Python, dtype: int32

In [160]:
# axis : {0, 1, 'index', 'columns'} index 行，columns 列
#     For Series input, axis to match Series index on

# axis = 0 行
df1.add(s,axis = 0)

Python   数学   En  Chinese
A     212  196  132      246
B     284  267  289      232
C      14   63  145       87
D     194  184  124      156
E     280  223  153      198
F     130   92  107      140

In [161]:
s2 = df1.loc['C']
s2

Python       7
数学          56
En         138
Chinese     80
Name: C, dtype: int32

In [164]:
display(df1,s2)

Python   数学   En  Chinese
A     106   90   26      140
B     142  125  147       90
C       7   56  138       80
D      97   87   27       59
E     140   83   13       58
F      65   27   42       75

Python       7
数学          56
En         138
Chinese     80
Name: C, dtype: int32

In [163]:
# axis = 1 列，根据列进行相加
# 采用广播
df1.add(s2,axis = 1)

Python   数学   En  Chinese
A     113  146  164      220
B     149  181  285      170
C      14  112  276      160
D     104  143  165      139
E     147  139  151      138
F      72   83  180      155

============================================

练习6：

1. 假设ddd是期中考试成绩，ddd2是期末考试成绩，请自由创建ddd2，并将其与ddd相加，求期中期末平均值。

2. 假设张三期中考试数学被发现作弊，要记为0分，如何实现？

3. 李四因为举报张三作弊立功，期中考试所有科目加100分，如何实现？

4. 后来老师发现有一道题出错了，为了安抚学生情绪，给每位学生每个科目都加10分，如何实现？

============================================